export PIPROV_SD_CARD_WRITABLE="/media/$USER/writable"
export PIPROV_SD_CARD_SYSTEMBOOT="/media/$USER/system-boot"
export PIPROV_WORKSTATION_KNOWNHOSTS="/home/$USER/.ssh/known_hosts"
export PIPROV_NET_SERVER_IP="192.168.1.50"
export PIPROV_NET_SUBNET_MASK_BITS="24"
export PIPROV_NET_GATEWAY_IP="192.168.1.1"
export PIPROV_NET_WIFI_NAME="My-Wifi"
export PIPROV_NET_WIFI_PASS="p@ssw0rd!"


